# Generated by Django 4.0.10 on 2025-01-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_recipe_tagds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tagds',
            new_name='tags',
        ),
    ]
